{% set name = "connected-components-3d" %}
{% set version = "3.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Apparently the tarball name uses underscores
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/connected_components_3d-{{ version }}.tar.gz
  sha256: 6f39c3679dc52ce5afd9c838b7573fc281f7ccfa583c9e42fac449c24ad9f30b

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - numpy
    - pbr
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - cc3d
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/connected-components-3d
  summary: Connected components on 2D and 3D images. Supports multiple labels.
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  dev_url: https://github.com/seung-lab/connected-components-3d/

extra:
  recipe-maintainers:
    - goanpeca
    - william-silversmith
    - stuarteberg
